// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#ifndef CLUSTER_H
#define CLUSTER_H

#include <ngrest/common/Service.h>
#include <restclient-cpp/restclient.h>
#include <iostream>
#include <string>
#include <sstream>
#include <fstream>
#include <vector>
#include <unistd.h>
//! Dummy description for the service
/*! Some detailed description of the service */
// '*location' comment sets resource path for this service
// *location: cluster
class cluster: public ngrest::Service
{
public:
    // Here is an example of service operation
    //! Dummy description for the operation
    /*! Some detailed description of the operation */
    // To invoke this operation from browser open: http://localhost:9098/cluster/World!
    //
    // '*location' metacomment sets path to operation relative to service operation.
    // Default value is operation name.
    // This will bind "echo" method to resource path: http://host:port/cluster/{text}
    // *location: /createVM
    //
    // '*method' metacomment sets HTTP method for the operation. GET is default method.
    // *method: POST
    //
    std::string createVM(const std::string& text);
    
    // *location: /createVMreq
    // *method: POST
    std::string createVMreq(int numVMs, int vcpu, int memory);
    
    // *location: /suspendVM
    // *method: POST
    std::string suspendVM(const std::string& text);
    
    // *location: /resumeVM
    // *method: POST
    std::string resumeVM(const std::string& text);
    
    // *location: /destroyVM/{text}
    // *method: DELETE
    std::string destroyVM(const std::string& text);


    // *location: /autoconfigVM
    // *method: POST
    std::string autoconfigVM(bool autoconfig);

    std::string destroyVMdir();

    // *location: /createVolume
    // *method: POST
    std::string createVolume(std::string domain, std::string cap, std::string unit);

    // *location: /getPoolList
    // *method: GET
    std::string getPoolList();

    // *location: /getVolumeList
    // *method: POST
    std::string getVolumeList(std::string pool);

    // *location: /attachVolumeToVM
    // *method: POST
    std::string attachVolumeToVM(std::string domain, std::string pool, std::string volume);


    // *location: /objectUpload
    // *method: POST
    std::string objectUpload(std::string fileName, std::string content);

    // *location: /objectDownload
    // *method: POST
    std::string objectDownload(std::string fileName);    

    
};


#endif // CLUSTER_H

